---
- name: show facts and run some condition
  hosts: localhost

  tasks:
    - name: show ansible facts
      debug:
        var: ansible_facts
    - name: run command on basis of facts
      command: echo "My os is ubuntu"
      when: ansible_facts['os_family'] == 'Ubuntu'